lib/openats/ats/router.ex
defmodule Openats.Ats.Router do
  # The registry must be explicitly provided here
  use AshJsonApi.Api.Router, api: Openats.Ats, registry: Openats.Ats.Registry
end

lib/openats_web/router.ex
defmodule OpenatsWeb.Router do
  use OpenatsWeb, :router

  import OpenatsWeb.UserAuth

  import AshAdmin.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {OpenatsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end
  
  pipeline :authenticated do
    plug :require_authenticated_user
  end

  scope "/", OpenatsWeb do
    pipe_through :browser
    pipe_through :authenticated

    get "/", PageController, :index
    live "/position_openings", PositionOpenings.Index
    live "/position_profiles", PositionProfiles.Index
    live "/position_profiles/new", PositionProfiles.New
    live "/position_profiles/:id", PositionProfiles.View
    live "/people/:id/edit", People.Edit
  end

  scope "/json_api" do
    pipe_through(:api)

    forward "/ats", Openats.Ats.Router
  end

  scope "/" do
    pipe_through :browser

    ash_admin "/admin"
  end

  # Other scopes may use custom stacks.
  # scope "/api", OpenatsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: OpenatsWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", OpenatsWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", OpenatsWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", OpenatsWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/openats_web/controllers/user_session_controller.ex
defmodule OpenatsWeb.UserSessionController do
  use OpenatsWeb, :controller

  alias Openats.Accounts
  alias OpenatsWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/openats_web/views/user_session_view.ex
defmodule OpenatsWeb.UserSessionView do
  use OpenatsWeb, :view
end

lib/openats_web/templates/user_session/new.html.heex
<div class="login-page">
  <div class="login-page__wrap">
    <div class="login-page__logo">
      <img src={Routes.static_path(@conn, "/images/logo.png")} width="80px" />
    </div>
    <div class="panel">
      <div class="panel__content">
        <.form let={f} for={@conn} action={Routes.user_session_path(@conn, :create)} as={:user}>
          <%= if @error_message do %>
            <div class="alert alert-danger">
              <p><%= @error_message %></p>
            </div>
          <% end %>
        
          <div class="form-control">
            <%= label f, :email, class: "form-label" %>
            <%= email_input f, :email, required: true, class: "text-field" %>
          </div>
        
          <div class="form-control">
            <%= label f, :password, class: "form-label" %>
            <%= password_input f, :password, required: true, class: "text-field" %>
          </div>
        
          <div class="form-check">
            <%= label f, :remember_me, "Keep me logged in for 60 days" %>
            <%= checkbox f, :remember_me %>
          </div>
        
          <div>
            <%= submit "Log in", class: "button button--full-width" %>
          </div>
        </.form>
      </div>
    </div>
    <div class="login-page__footnote">
      <%= link "Register", to: Routes.user_registration_path(@conn, :new) %> |
      <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
    </div>
  </div>
</div>